languageCode = "en"
languageName = "English"
weight = 1
#title = "Blowfish"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/egcs_logo.png"
  description = "A powerful, lightweight theme for Hugo."

[params.author]
  name = "Evergreen Counseling Services"
  email = "info@egcs.health"
  image = "img/egcs_logo.png"
  headline = "A powerful, lightweight theme for Hugo."
  bio = "A powerful, lightweight theme for Hugo."
  links = [
    { facebook = "https://twitter.com/burufugu" },
    { intagram = "https://github.com/nunocoracao/blowfish" },
  ]