languageCode = "en"
languageName = "English"
weight = 1
#title = "Blowfish"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/egcs_logo.png"
  description = "Individualized Counseling for All Ages You may be wondering if counseling is the next step for you or a loved one. It can feel overwhelming, but don't worry. We are here to help."

[params.author]
  name = "Evergreen Counseling Services"
  email = "info@egcs.health"
  image = "img/egcs_logo.png"
  #headline = "A powerful, lightweight theme for Hugo."
  bio = "A powerful, lightweight theme for Hugo."
  links = [
    { facebook = "https://facebook.com/evergreencounselingservices" },
    { instagram = "https://instagram.com/evergreencounselingservices" },
  ]