# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Counseling"
  weight = 10
[[main]]
  name = "Individual Counseling"
  parent = "Counseling"
  pageRef = "/services/individual-counseling"
  weight = 10
[[main]]
  name = "Couples Counseling"
  parent = "Counseling"
  pageRef = "/services/couples-counseling"
  weight = 20
[[main]]
  name = "Services"
  weight = 20
[[main]]
  name = "Supervision & Continuing Education"
  parent = "Services"
  pageRef = "/services/clinical-supervision"
  weight = 10
[[main]]
  name = "Classes & Workshops"
  parent = "Services"
  pageRef = "/classes/anger-management"
  weight = 20
[[main]]
  name = "Resources"
  pageRef = "docs"
  weight = 40
[[main]]
  name = "Client Portal"
  pre = "hipaa"
  url = "https://egcs.theranest.com/home/"
  weight = 60
[[subnavigation]]
  name = "Blog"
  pageRef = "blog"
  weight = 10
#[[subnavigation]]
#  name = "Our Team"
#  pageRef = "counselors"
#  wight = 10
# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10
#
# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
