# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "egcs"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = false

enableSearch = false
enableCodeCopy = true

replyByEmail = false

mainSections = ["docs"]
# robots = ""

disableImageOptimization = false
disableTextInHeader = true
# backgroundImageWidth = 1200

#defaultBackgroundImage = "/img/background.svg"
defaultFeaturedImage = "/img/featured.svg"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

[header]
  layout = "basic" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = false

[homepage]
  layout = "custom" # valid options: page, profile, hero, card, background, custom
  # homepageImage = "/img/iceland.jpg" # used in: hero, and card
  showRecent = false
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "docs"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background

[article]
  showDate = false
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = false
  showAuthor = true
  # showAuthorBottom = false
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = true
  editURL = "https://github.com/andrewamason/egcs/tree/main/content"
  editAppendPath = true
  seriesOpened = true
  showHeadingAnchors = false
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = false
  showRelatedContent = true
  relatedContentLimit = 6
  showTaxonomies = false 
  showAuthorsBadges = true 
  showWordCount = false
  sharingLinks = false
  # sharingLinks = [ "linkedin", "twitter", "bluesky", "reddit", "whatsapp", "telegram", "pinterest", "facebook", "email"]
  showZenMode = false

[list]
  showHero = true
  heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = true
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = true
  orderByWeight = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  cardView = false

[term]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  
[firebase]
  apiKey = "AIzaSyB2Qcty4TBE1VqmNpkTkXnvr-rTtQla73Q"
  authDomain = "egcs-a21ba.firebaseapp.com"
  projectId = "egcs-a21ba"
  storageBucket = "egcs-a21ba.firebasestorage.app"
  messagingSenderId = "838046952637"
  appId = "1:838046952637:web:184d534d8dd298c07fdbd4"
  measurementId = "G-TDF3BDLT1J"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[umamiAnalytics]
  # websiteid = "ABC12345"
  # domain = "llama.yoursite.com"
  # dataDomains = "yoursite.com,yoursite2.com"
  # scriptName = ""
  # enableTrackEvent = false

[selineAnalytics]
  # token = "XXXXXX"
  # enableTrackEvent = false

#[buymeacoffee]
#  identifier = "nunocoracao"
#  emoji = ""
#  globalWidget = true
#  globalWidgetMessage = "Connect now"
#  globalWidgetColor = "#FFDD00"
#  globalWidgetPosition = "Right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

[rssnext]
  # feedId = ""
  # userId = ""